### ISSUE TITLE
执行出错

### ISSUE THREAD

**Issue by dovanchan** [hzy46/fast-neural-style-tensorflow#10]
python eval.py --model_file </Users/DOVAN/Downloads/mosaic.ckpt-done> --image_file /Users/DOVAN/Desktop/photo.jpg

Traceback (most recent call last):
  File "eval.py", line 62, in <module>
    tf.app.run()
  File "/Users/DOVAN/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval.py", line 38, in main
    image = reader.get_image(FLAGS.image_file, height, width, image_preprocessing_fn)
  File "/Users/DOVAN/deeprely/fast-neural-style-tensorflow/reader.py", line 10, in get_image
    return preprocess_fn(image, height, width)
  File "/Users/DOVAN/deeprely/fast-neural-style-tensorflow/preprocessing/preprocessing_factory.py", line 70, in preprocessing_fn
    image, output_height, output_width, is_training=is_training, **kwargs)
  File "/Users/DOVAN/deeprely/fast-neural-style-tensorflow/preprocessing/vgg_preprocessing.py", line 388, in preprocess_image
    resize_side_min)
  File "/Users/DOVAN/deeprely/fast-neural-style-tensorflow/preprocessing/vgg_preprocessing.py", line 353, in preprocess_for_eval
    image = _central_crop([image], output_height, output_width)[0]
  File "/Users/DOVAN/deeprely/fast-neural-style-tensorflow/preprocessing/vgg_preprocessing.py", line 200, in _central_crop
    crop_height, crop_width))
  File "/Users/DOVAN/deeprely/fast-neural-style-tensorflow/preprocessing/vgg_preprocessing.py", line 76, in _crop
    tf.pack([crop_height, crop_width, original_shape[2]]))
AttributeError: 'module' object has no attribute 'pack'

这个是什么原因？ 
当我尝试卸载之前版本的tensorflow后，安装TF-slim后，又报错了

DOVANtekiMacBook-Pro:fast-neural-style-tensorflow DOVAN$ sudo pip install --upgrade $TF_BINARY_URL
Password:
The directory '/Users/DOVAN/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/DOVAN/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.

请问是什么原因，该怎么解决～

**Comment by dovanchan** [comment]
DOVANtekiMacBook-Pro:fast-neural-style-tensorflow DOVAN$ python eval.py --model_file /Users/DOVAN/Downloads/mosaic.ckpt-done --image_file /Users/DOVAN/Desktop/dovan.jpg
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
INFO:tensorflow:Image size: 2000x2123
Traceback (most recent call last):
  File "eval.py", line 62, in <module>
    tf.app.run()
  File "/Users/DOVAN/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval.py", line 38, in main
    image = reader.get_image(FLAGS.image_file, height, width, image_preprocessing_fn)
  File "/Users/DOVAN/deeprely/fast-neural-style-tensorflow/reader.py", line 10, in get_image
    return preprocess_fn(image, height, width)
  File "/Users/DOVAN/deeprely/fast-neural-style-tensorflow/preprocessing/preprocessing_factory.py", line 70, in preprocessing_fn
    image, output_height, output_width, is_training=is_training, **kwargs)
  File "/Users/DOVAN/deeprely/fast-neural-style-tensorflow/preprocessing/vgg_preprocessing.py", line 388, in preprocess_image
    resize_side_min)
  File "/Users/DOVAN/deeprely/fast-neural-style-tensorflow/preprocessing/vgg_preprocessing.py", line 353, in preprocess_for_eval
    image = _central_crop([image], output_height, output_width)[0]
  File "/Users/DOVAN/deeprely/fast-neural-style-tensorflow/preprocessing/vgg_preprocessing.py", line 200, in _central_crop
    crop_height, crop_width))
  File "/Users/DOVAN/deeprely/fast-neural-style-tensorflow/preprocessing/vgg_preprocessing.py", line 76, in _crop
    tf.pack([crop_height, crop_width, original_shape[2]]))
AttributeError: 'module' object has no attribute 'pack'


这是用自带模型后的报错，请问该如何解决

**Comment by chuxuezhi01** [comment]
我也是运行时这样报错，请问你找到解决办法了吗？

**Comment by jiarongqiu** [comment]
由于tensorflow升级到了1.0所产生的一些变化
tf.pack  should be renamed to tf.stack

后面还会有很多的报错，解决方案都在这里 https://www.tensorflow.org/install/migration

**Comment by hzy46** [comment]
关于api出错

Tensorflow更新到1.0后大量api发生改变，我也做了新的调整。Tensorflow 1.0的用户请使用最新的commit，细节参考README.md。

谢谢支持！

-------------------------------------
About Error when calling Tensorflow API

After Tensorflow 1.0, many APIs have changed. Now I also changed the API to 1.0. Please see the latest commit and the latest README.md for details. 

Thank you for your support!
