### ISSUE TITLE
自己训练的模型因为cpu速度慢中断了 生产如下的训练过程中写入的文件不能用吗？eval的时候会报错

### ISSUE THREAD

**Issue by 625673575** [hzy46/fast-neural-style-tensorflow#12]
fast-style-model.ckpt-600.data-00000-of-00001
fast-style-model.ckpt-600.index
fast-style-model.ckpt-600.meta

**Comment by 625673575** [comment]
D:\CommonCode\fast-neural-style-tensorflow>python eval.py --model_file michelangelo.ckpt --image_file img/test.jpg
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
INFO:tensorflow:Image size: 712x474
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Data loss: Unable to open table file D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Data loss: Unable to open table file D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Data loss: Unable to open table file D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Data loss: Unable to open table file D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Data loss: Unable to open table file D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Data loss: Unable to open table file D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Data loss: Unable to open table file D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Data loss: Unable to open table file D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Data loss: Unable to open table file D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Data loss: Unable to open table file D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Data loss: Unable to open table file D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Data loss: Unable to open table file D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Data loss: Unable to open table file D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Data loss: Unable to open table file D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Data loss: Unable to open table file D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Data loss: Unable to open table file D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1022, in _do_call
    return fn(*args)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1004, in _run_fn
    status, run_metadata)
  File "C:\Program Files\Anaconda3\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
         [[Node: save/RestoreV2_13 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_13/tensor_names, save/RestoreV2_13/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval.py", line 62, in <module>
    tf.app.run()
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval.py", line 45, in main
    saver.restore(sess, FLAGS.model_file)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1428, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 767, in run
    run_metadata_ptr)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
         [[Node: save/RestoreV2_13 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_13/tensor_names, save/RestoreV2_13/shape_and_slices)]]

Caused by op 'save/RestoreV2_13', defined at:
  File "eval.py", line 62, in <module>
    tf.app.run()
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval.py", line 42, in main
    saver = tf.train.Saver(tf.global_variables())
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1040, in __init__
    self.build()
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1070, in build
    restore_sequentially=self._restore_sequentially)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 675, in build
    restore_sequentially, reshape)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

DataLossError (see above for traceback): Unable to open table file D:\CommonCode\fast-neural-style-tensorflow\michelangelo.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
         [[Node: save/RestoreV2_13 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_13/tensor_names, save/RestoreV2_13/shape_and_slices)]]


D:\CommonCode\fast-neural-style-tensorflow>

**Comment by 625673575** [comment]
自己忙活了好久原来可以直接传入fast-style-model.ckpt-600 作为模型

**Comment by chuxuezhi01** [comment]
@625673575 你是用的作者的源代码训练的吗？你的tensorflow的版本是？

**Comment by 625673575** [comment]
@chuxuezhi01 我用的1.0版本 自己改了源码升级的

**Comment by chuxuezhi01** [comment]
@625673575 你能将你改后的源码分享一下吗？我一直改一直报错，希望得到你的帮助。

**Comment by 625673575** [comment]
@chuxuezhi01 作者已经改了代码 主要就是替换几个过时的函数
