### ISSUE TITLE
ERROR：The tensor returned for EncodeJpeg:0 was not valid.

### ISSUE THREAD

**Issue by zhaoxinlu** [hzy46/fast-neural-style-tensorflow#22]
Traceback (most recent call last):
  File "eval.py", line 76, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval.py", line 67, in main
    img.write(sess.run(tf.image.encode_jpeg(generated)))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: The tensor returned for EncodeJpeg:0 was not valid.

**Comment by hzy46** [comment]
your python version&TensorFlow version?

**Comment by zhaoxinlu** [comment]
python 2.7.6
tensorflow 1.1.0
tensorflow-gpu 1.1.0

**Comment by hzy46** [comment]
Seems that the tensor "generated" is not valid. Could you print the value of "generated"? (sess.run(generated))

**Comment by zhaoxinlu** [comment]
tensorflow.python.framework.errors_impl.InvalidArgumentError: The tensor returned for Squeeze_1:0 was not valid.
