### ISSUE TITLE
I've got an error message "Invalid JPEG data, size 53248".

### ISSUE THREAD

**Issue by GongXinyuu** [hzy46/fast-neural-style-tensorflow#35]
I don't know how it happened. It goes well in first hundreds of iterations. Maybe there's some problems with my mscoco dataset? And I'm trying to print the name of the image with problem.

Here's the error message.
> Traceback (most recent call last):
  File "/home/gongxinyu/Deeplearning/CNN/source_code/fast-neural-style-tensorflow_gxy/train.py", line 158, in <module>
    main(FLAGS)
  File "/home/gongxinyu/Deeplearning/CNN/source_code/fast-neural-style-tensorflow_gxy/train.py", line 151, in main
    coord.join(threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1175, in _single_operation_run
    target_list_as_strings, status, None)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid JPEG data, size 53248
	 [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](ReaderReadV2:1)]]
	 [[Node: ResizeBilinear/_91 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_53_ResizeBilinear", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by hzy46** [comment]
There are some broken images in your dataset probably. 

Try to write a script with "tf.image.decode_jpeg" to decode all the images to find out the broken ones.

**Comment by GongXinyuu** [comment]
Thx!
