### ISSUE TITLE
python3.6下train模型出现错误

### ISSUE THREAD

**Issue by siyuanzhuang** [hzy46/fast-neural-style-tensorflow#40]
python3.6,tensorflow1.3环境下运行出现
INFO:tensorflow:Scale of 0 disables regularizer.
2017-11-02 17:15:01.143690: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
INFO:tensorflow:Use pretrained model pretrained/vgg_16.ckpt
INFO:tensorflow:Restoring parameters from pretrained/vgg_16.ckpt
INFO:tensorflow:Target style pattern is saved to: generated/target_style_mosaic.jpg.
INFO:tensorflow:Scale of 0 disables regularizer.
Traceback (most recent call last):
  File "E:/web/image_style/fast-neural-style-tensorflow-master/train.py", line 146, in <module>
    main(FLAGS)
  File "E:/web/image_style/fast-neural-style-tensorflow-master/train.py", line 45, in main
    generated = model.net(processed_images, training=True)
  File "E:\web\image_style\fast-neural-style-tensorflow-master\model.py", line 104, in net
    conv1 = tf.nn.relu(instance_norm(conv2d(image, 3, 32, 9, 1)))
  File "E:\web\image_style\fast-neural-style-tensorflow-master\model.py", line 9, in conv2d
    x_padded = tf.pad(x, [[0, 0], [kernel / 2, kernel / 2], [kernel / 2, kernel / 2], [0, 0]], mode=mode)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1684, in pad
    name=name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1738, in _mirror_pad
    mode=mode, name=name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 589, in apply_op
    param_name=input_name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'paddings' has DataType float32 not in list of allowed values: int32, int64
这个错误提示？是因为不支持python3的原因吗？

**Comment by siyuanzhuang** [comment]
代码需要怎样修改呢？请指教！谢谢

**Comment by hzy46** [comment]
int(kernel / 2)
