### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mqchen1993** [hzy46/fast-neural-style-tensorflow#49]
Traceback (most recent call last):
  File "train.py", line 146, in <module>
    main(FLAGS)
  File "train.py", line 44, in main
    'train2014/', image_preprocessing_fn, epochs=FLAGS.epoch)
  File "/root/fast-neural-style-tensorflow/reader.py", line 18, in image
    png = filenames[0].lower().endswith('png')  # If first file is a png, assume they all are
IndexError: list index out of range

Thanks!

**Comment by mqchen1993** [comment]
@hzy46
