### ISSUE TITLE
运行train.py报错ResourceExhaustedError

### ISSUE THREAD

**Issue by blahBlahhhJ** [hzy46/fast-neural-style-tensorflow#52]
cmd里训练命令为
`python train.py -c conf\scream.yml`
提示

> Traceback (most recent call last):
  File "train.py", line 146, in <module>
    main(FLAGS)
  File "train.py", line 118, in main
    _, loss_t, step = sess.run([train_op, loss, global_step])
  File "D:\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    run_metadata)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[4,128,278,278] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: deconv1/conv_transpose/conv/conv-0-TransposeNHWCToNCHW-LayoutOptimizer = Transpose[T=DT_FLOAT, Tperm=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](deconv1/conv_transpose/conv/MirrorPad, PermConstNHWCToNCHW-LayoutOptimizer)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
        
使用的是tensorflow-gpu.显卡是GTX-960M.我觉得没有理由跑不起来...(batch size已经4了)
请问是什么原因导致这种情况发生,我能如何修改让它运行?

**Comment by hzy46** [comment]
batch_size改成1或者2看看

**Comment by blahBlahhhJ** [comment]
有道理...在batch size=1的时候终于动了
