### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by soyeduardorico** [hzy46/fast-neural-style-tensorflow#65]
I am relatively new to this field. I am trying to train the model ith my own images. However it is taking quite long for each training session (in excess of 12 hours) and I woul dlike to know whether I can make it faster. One option I thought was to change the size of the image in the yaml file and bring it down:

## The size, the iter number to run
image_size: 128
batch_size: 4
epoch: 2

However it seems that it finds problems down the line since the vgg16 is trying to look for images 256 size. Going through model.py I can see that the def net(image, training): has some of these details to be scripted, however I am not sure I can know how to do it.

def net(image, training):
    # Less border effects when padding a little before passing through ..
    image = tf.pad(image, [[0, 0], [10, 10], [10, 10], [0, 0]], mode='REFLECT')

    with tf.variable_scope('conv1'):
        conv1 = relu(instance_norm(conv2d(image, 3, 32, 9, 1)))
    with tf.variable_scope('conv2'):
        conv2 = relu(instance_norm(conv2d(conv1, 32, 64, 3, 2)))
    with tf.variable_scope('conv3'):
        conv3 = relu(instance_norm(conv2d(conv2, 64, 128, 3, 2)))
    with tf.variable_scope('res1'):
        res1 = residual(conv3, 128, 3, 1)
    with tf.variable_scope('res2'):
        res2 = residual(res1, 128, 3, 1)
    with tf.variable_scope('res3'):
        res3 = residual(res2, 128, 3, 1)
    with tf.variable_scope('res4'):
        res4 = residual(res3, 128, 3, 1)
    with tf.variable_scope('res5'):
        res5 = residual(res4, 128, 3, 1)
    # print(res5.get_shape())
    with tf.variable_scope('deconv1'):
        # deconv1 = relu(instance_norm(conv2d_transpose(res5, 128, 64, 3, 2)))
        deconv1 = relu(instance_norm(resize_conv2d(res5, 128, 64, 3, 2, training)))
    with tf.variable_scope('deconv2'):
        # deconv2 = relu(instance_norm(conv2d_transpose(deconv1, 64, 32, 3, 2)))
        deconv2 = relu(instance_norm(resize_conv2d(deconv1, 64, 32, 3, 2, training)))
    with tf.variable_scope('deconv3'):
        # deconv_test = relu(instance_norm(conv2d(deconv2, 32, 32, 2, 1)))
        deconv3 = tf.nn.tanh(instance_norm(conv2d(deconv2, 32, 3, 9, 1)))

    y = (deconv3 + 1) * 127.5

Is there a simple way to reduce image size or accelerate the process? 

Thanks in advance

**Comment by soyeduardorico** [comment]
This is the entire log I am getting, in case it helps (the last bit it what makes me think it is an issue with size):

runfile('C:/Users/ucbqeri/Documents/GitHub/fast-neural-style-tensorflow/train.py', wdir='C:/Users/ucbqeri/Documents/GitHub/fast-neural-style-tensorflow')
C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

INFO:tensorflow:Scale of 0 disables regularizer.
WARNING:tensorflow:From C:\Users\ucbqeri\Documents\GitHub\fast-neural-style-tensorflow\preprocessing\vgg_preprocessing.py:269: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py:423: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\ucbqeri\Documents\GitHub\fast-neural-style-tensorflow\preprocessing\vgg_preprocessing.py:277: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
C:\Users\ucbqeri\Documents\GitHub\fast-neural-style-tensorflow\utils.py:50: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  FLAGS = Flag(**yaml.load(f))
Traceback (most recent call last):

  File "<ipython-input-131-8d036b22e79e>", line 1, in <module>
    runfile('C:/Users/ucbqeri/Documents/GitHub/fast-neural-style-tensorflow/train.py', wdir='C:/Users/ucbqeri/Documents/GitHub/fast-neural-style-tensorflow')

  File "C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/ucbqeri/Documents/GitHub/fast-neural-style-tensorflow/train.py", line 147, in <module>
    main(FLAGS)

  File "C:/Users/ucbqeri/Documents/GitHub/fast-neural-style-tensorflow/train.py", line 26, in main
    style_features_t = losses.get_style_features(FLAGS)

  File "C:\Users\ucbqeri\Documents\GitHub\fast-neural-style-tensorflow\losses.py", line 52, in get_style_features
    _, endpoints_dict = network_fn(images, spatial_squeeze=False)

  File "C:\Users\ucbqeri\Documents\GitHub\fast-neural-style-tensorflow\nets\nets_factory.py", line 105, in network_fn
    return func(images, num_classes, is_training=is_training, **kwargs)

  File "C:\Users\ucbqeri\Documents\GitHub\fast-neural-style-tensorflow\nets\vgg.py", line 151, in vgg_16
    net = slim.conv2d(net, 4096, [7, 7], padding='VALID', scope='fc6')

  File "C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)

  File "C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1155, in convolution2d
    conv_dims=2)

  File "C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)

  File "C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1058, in convolution
    outputs = layer.apply(inputs)

  File "C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1227, in apply
    return self.__call__(inputs, *args, **kwargs)

  File "C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\layers\base.py", line 530, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)

  File "C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)

  File "C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 194, in call
    outputs = self._convolution_op(inputs, self.kernel)

  File "C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 966, in __call__
    return self.conv_op(inp, filter)

  File "C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 591, in __call__
    return self.call(inp, filter)

  File "C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 208, in __call__
    name=self.name)

  File "C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1112, in conv2d
    data_format=data_format, dilations=dilations, name=name)

  File "C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)

  File "C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)

  File "C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)

  File "C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1823, in __init__
    control_input_ops)

  File "C:\Users\ucbqeri\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))

ValueError: Negative dimension size caused by subtracting 7 from 4 for 'vgg_16/fc6/Conv2D' (op: 'Conv2D') with input shapes: [1,4,4,512], [7,7,512,4096].
