### ISSUE TITLE
tensorflow 1.0RC

### ISSUE THREAD

**Issue by edongyu** [hzy46/fast-neural-style-tensorflow#7]
使用tensorflow 1.0rc遇到两个问题，经过简单修改已经可以正常运行

eval.py 

报错：
File "eval.py", line 29, in main
  image = sess.run(tf.image.decode_jpeg(img.read()))
AttributeError: 'weakref' object has no attribute 'run'

修改 ： tf.Session().as_default() 改为 tf.Session()

**Comment by edongyu** [comment]
model.py

报错：
File "/fast-neural-style-tensorflow-master/model.py", line 42, in resize_conv2d
  x_resized = tf.image.resize_images(x, [new_height, new_width], tf.image.ResizeMethod.NEAREST_NEIGHBOR)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/image_ops.py", line 781, in resize_images
  raise ValueError('new_height must be a scalar integer')
ValueError: new_height must be a scalar integer

修改 ：
tf.image.resize_images() 方法的参数有所修改，需要将
x_resized = tf.image.resize_images(x, [new_height, new_width], tf.image.ResizeMethod.NEAREST_NEIGHBOR)
改为
x_resized = tf.image.resize_images(x, new_height, new_width, tf.image.ResizeMethod.NEAREST_NEIGHBOR)

**Comment by edongyu** [comment]
nets/vgg.py

运行train.py -c conf/wave.yml

报错：
Traceback (most recent call last):
  File "train.py", line 134, in <module>
    main(FLAGS)
  File "train.py", line 25, in main
    style_features_t = losses.get_style_features(FLAGS)
  File "/tensorflow/fast-neural-style/fast-neural-style-tensorflow-master/losses.py", line 47, in get_style_features
    _, endpoints_dict = network_fn(images, spatial_squeeze=False)
  File "/tensorflow/fast-neural-style/fast-neural-style-tensorflow-master/nets/nets_factory.py", line 105, in network_fn
    return func(images, num_classes, is_training=is_training, **kwargs)
  File "/tensorflow/fast-neural-style/fast-neural-style-tensorflow-master/nets/vgg.py", line 176, in vgg_16
    end_points = slim.utils.convert_collection_to_dict(end_points_collection)
AttributeError: 'module' object has no attribute 'convert_collection_to_dict'

修改：
176行 end_points = slim.utils.convert_collection_to_dict(end_points_collection)
改为 end_points = dict(tf.get_collection(end_points_collection))
